package com.chris.bookstore.enums;

public enum Privilege {
    CREATE_BOOKS,
    EDIT_BOOKS,
    DELETE_BOOKS,
    CREATE_CATEGORIES,
    EDIT_CATEGORIES,
    DELETE_CATEGORIES,
    READ_ORDERS,
    UPDATE_ORDER_STATUS_CONFIRMED,
    UPDATE_ORDER_STATUS_DELIVERED,
    UPDATE_ORDER_STATUS_SHIPPED,
    UPDATE_ORDER_STATUS_CANCELLED,
    EDIT_SHOP,
    TOGGLE_SHOP_AVAILABILITY,
}
